--DROP SCHEMA shopper CASCADE;
CREATE SCHEMA shopper;

CREATE TABLE "shopper"."users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(50) NOT NULL,
  "username" varchar(50) NOT NULL,
  "password" varchar(50) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "shopper"."products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(250),
  "price" decimal(10,2) NOT NULL,
  "stock" int NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "shopper"."orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shopping_cart_id" int,
  "coupon_id" int,
  "subtotal" decimal(10,2),
  "discount" decimal(10,2),
  "total" decimal(10,2),
  "order_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "shopper"."coupons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) NOT NULL,
  "discount_percent" decimal(10,2) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "used" boolean NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "shopper"."shopping_carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "total" decimal(10,2),
  "active" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "shopper"."shopping_cart_details" (
  "cart_id" int,
  "product_id" int,
  "quant" int,
  "unit_price" decimal(10,2),
  "subtotal" decimal(10,2),
  "created_at" timestamp
);


CREATE TABLE "shopper"."seasonal_discounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "percentage" decimal(10,2) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "created_at" timestamp
);

ALTER TABLE "shopper"."shopping_cart_details" ADD FOREIGN KEY ("product_id") REFERENCES "shopper"."products" ("id");

ALTER TABLE "shopper"."seasonal_discounts" ADD FOREIGN KEY ("product_id") REFERENCES "shopper"."products" ("id");

ALTER TABLE "shopper"."shopping_carts" ADD FOREIGN KEY ("user_id") REFERENCES "shopper"."users" ("id");

ALTER TABLE "shopper"."shopping_cart_details" ADD FOREIGN KEY ("cart_id") REFERENCES "shopper"."shopping_carts" ("id");

ALTER TABLE "shopper"."orders" ADD FOREIGN KEY ("shopping_cart_id") REFERENCES "shopper"."shopping_carts" ("id");

ALTER TABLE "shopper"."orders" ADD FOREIGN KEY ("coupon_id") REFERENCES "shopper"."coupons" ("id");



-- Insert Data

INSERT INTO shopper.Users (email, username, password, created_at) 
VALUES 
('admin@example.com', 'admin', 'password123', CURRENT_TIMESTAMP),
('otro@example.com', 'otro', 'securepass', CURRENT_TIMESTAMP);

INSERT INTO shopper.Products (name, description, price, stock, created_at) 
VALUES 
('Laptop', '15-inch gaming laptop', 1200.00, 10, CURRENT_TIMESTAMP),
('Smartphone', 'Latest Android phone', 800.00, 20, CURRENT_TIMESTAMP),
('Headphones', 'Wireless over-ear headphones', 150.00, 50, CURRENT_TIMESTAMP),
('Smartwatch', 'Fitness tracking smartwatch', 200.00, 30, CURRENT_TIMESTAMP);

INSERT INTO shopper.Coupons (code, discount_percent, start_date, end_date, used, created_at) 
VALUES 
('SAVE10', 10.00, '2024-01-01', '2024-12-31', FALSE,  CURRENT_TIMESTAMP),
('FREESHIP', 5.00, '2024-06-01', '2024-12-31', FALSE, CURRENT_TIMESTAMP);

--===============================

/*INSERT INTO shopper.shopping_carts(user_id, total, active, created_at, updated_at) 
VALUES 
(1, 0.00, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 0.00, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO shopper.shopping_cart_details (cart_id, product_id, quant, unit_price, subtotal, created_at) 
VALUES 
(1, 1, 1, 1200.00, 1200.00, CURRENT_TIMESTAMP),
(1, 3, 2, 150.00, 300.00, CURRENT_TIMESTAMP),
(2, 2, 1, 800.00, 800.00, CURRENT_TIMESTAMP);

INSERT INTO shopper.seasonal_discounts (id, product_id, percentage, start_date, end_date, created_at) 
VALUES 
(1, 1, 15.00, '2024-11-01', '2024-11-30', CURRENT_TIMESTAMP),
(2, 3, 20.00, '2024-12-01', '2024-12-31', CURRENT_TIMESTAMP);

INSERT INTO shopper.orders (id, shopping_cart_id, coupon_id, subtotal, discount, total, order_date, created_at) 
VALUES 
(1, 1, 1, 1500.00, 150.00, 1350.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, 2, 800.00, 40.00, 760.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);*/


